codecov:
  notify:
    require_ci_to_pass: yes

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  # ignore folders and all its contents
  - "/home/travis/.phpenv/.*"
  - "php-zephir-parser/.*"
  - ".phpunit/.*"
