language: php
php:
  - '7.4snapshot'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 5
  quiet: true

addons:
  apt:
    packages:
      - gdb
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/.local/opt
    - .phpunit

env:
  global:
    - RE2C_VERSION="1.1.1"
    - ZEPHIR_PARSER_VERSION="v1.3.0"
    # TODO: See Library/StatementsBlock.php
    # - ZEPHIR_DEBUG=true
    - COLLECT_COVERAGE=true
    - BOX_VERSION=3.3.1
    - BUILD_PHAR=false
    - PATH="${HOME}/bin:${PATH}"
    - TRAVIS_COMMIT_LOG=`git log --format=fuller -5`

before_install:
  - |
      # General settings
      stty cols 120

      # Export build/test environment variables
      export SYMFONY_PHPUNIT_DIR=$(pwd)/.phpunit
      export PHP_VERNUM="$(php-config --vernum)"

      if [ ! -z "${GITHUB_TOKEN}" ]; then
        composer config github-oauth.github.com ${GITHUB_TOKEN}
        printf "Add Github token\n"
      fi

      [ -d ~/bin ] || mkdir ~/bin

      # Core dump settings
      ulimit -c unlimited -S || true
      echo '/tmp/core.%e.%p.%t' | sudo tee /proc/sys/kernel/core_pattern

      # Hide "You are in 'detached HEAD' state" message
      git config --global advice.detachedHead false

      # Box does not work with PHP 7.4
      if [ "$PHP_VERNUM" -ge "70100" ] && [ "$PHP_VERNUM" -lt "70400" ]; then
        export BUILD_PHAR=true
      fi

      if [ "$PHP_VERNUM" -ge "70400" ]; then
        # Do not collect code coverage for PHP 7.4
        export COLLECT_COVERAGE=false

        # Temporary until we release parser with PHP 7.4 support
        export ZEPHIR_PARSER_VERSION=development
      fi
install:
  - .ci/install-prereqs.sh
  - .ci/install-re2c.sh $RE2C_VERSION
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then composer config platform.php 7.0.33; echo "Preparing to deploy"; fi
  - travis_retry composer install $flags
  - |
    # Prepare Zephir executable
    if [ "$BUILD_PHAR" = "true" ]; then
      printf "Build Zephit PHAR\n"
      .ci/build-phar.sh
    else
      printf "Use Zephir from source\n"
      ln -s $(pwd)/zephir ${HOME}/bin/zephir
    fi

before_script:
  - .ci/build-test-ext.sh
  - cat .ci/travis.ini >> $(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Does not ready yet
  - if [ "$PHP_VERNUM" -ge "70400" ]; then phpenv config-rm xdebug.ini || true; fi

script:
  - zephir --ansi
  - .ci/run-tests.sh
  - (cd unit-tests/sharness && make)

after_success:
  - .ci/after-success.sh

after_failure:
  - .ci/after-failure.sh

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env:
        - CHECK=php-cs-fixer
        - COLLECT_COVERAGE=false
      install:
        - wget --no-clobber -O $HOME/bin/php-cs-fixer https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
      before_script:
        - chmod +x $HOME/bin/php-cs-fixer
      script:
        - php-cs-fixer fix --diff --dry-run -v

    - stage: Static Code Analysis
      php: 7.2
      env:
        - CHECK=PHP_CodeSniffer
        - COLLECT_COVERAGE=false
      install:
        - wget --no-clobber -O $HOME/bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      before_script:
        - chmod +x $HOME/bin/phpcs
      script:
        - phpcs

notifications:
  email: false

after_script:
  - printf "$TRAVIS_COMMIT_RANGE\n"
  - printf "$TRAVIS_COMMIT_LOG\n"

before_deploy:
  - git config --global user.name cicdbot
  - git config --global user.email team@zephir-lang.com

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: zephir.phar
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'
  repo: phalcon/zephir
